name: Schedule Worker

on: workflow_dispatch

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: szenius/set-timezone@v1.0 # 设置执行环境的时区
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: actions/setup-python@v1 # 使用python装配器
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Run
        run: |
          python -v
          python test.py

      - name: commit
         run: |
          git add mmzxsp
          git commit -m "update" -a



# on: workflow_dispatch
 
# jobs:
#   run:
#     runs-on: ubuntu-latest
 
#     steps:
#     - name: Hello World
#       run: |
#         echo My name is P3TERX.
#         echo Hello World!
